# Generated by Django 5.2.13 on 2026-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantbankaccount',
            name='account_name',
            field=models.CharField(default='Primary Account', max_length=100),
        ),
        migrations.AddField(
            model_name='merchantbankaccount',
            name='bank_name',
            field=models.CharField(default='HDFC Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='merchantbankaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
