# Generated by Django 5.2.13 on 2026-04-25 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(message='Must be a valid UUID', regex='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$')])),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=16)),
                ('response', models.JSONField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='merchants.merchant')),
            ],
            options={
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_idem_status_created'), models.Index(fields=['merchant', 'created_at'], name='idx_idem_merchant_created')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'key'), name='uq_idem_merchant_key'), models.CheckConstraint(condition=models.Q(models.Q(('http_status__isnull', True), ('response__isnull', True), ('status', 'PROCESSING')), models.Q(('http_status__isnull', False), ('response__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='ck_idem_status_payload_consistency'), models.CheckConstraint(condition=models.Q(('http_status__isnull', True), models.Q(('http_status__gte', 100), ('http_status__lte', 599)), _connector='OR'), name='ck_idem_http_status_range')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(message='Must be a valid UUID', regex='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$')])),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.merchantbankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.merchant')),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['merchant', 'status', 'created_at'], name='idx_payout_m_status_cr'), models.Index(fields=['status', 'created_at'], name='idx_payout_status_cr'), models.Index(fields=['status', 'updated_at'], name='idx_payout_status_upd'), models.Index(fields=['status', 'processing_started_at', 'attempts'], name='idx_payout_status_proc_att'), models.Index(fields=['merchant', 'created_at'], name='idx_payout_merchant_cr')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_payout_amount_positive'), models.UniqueConstraint(fields=('merchant', 'idempotency_key'), name='uq_payout_merchant_idempotency')],
            },
        ),
    ]
