# Generated by Django 5.2.13 on 2026-04-26 13:34

import payouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='expires_at',
            field=models.DateTimeField(default=payouts.models.default_expiry),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at'], name='idx_idem_expires'),
        ),
    ]
