# Generated by Django 5.2.13 on 2026-04-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reference', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='idx_ledger_merchant_created'), models.Index(fields=['reference'], name='idx_ledger_reference')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_ledger_amount_non_zero'), models.UniqueConstraint(fields=('merchant', 'reference'), name='uq_ledger_merchant_reference')],
            },
        ),
    ]
