# Generated by Django 5.2.13 on 2026-04-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('merchants', '0002_merchantbankaccount_account_name_and_more'),
        ('payouts', '0002_idempotencykey_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('hold', 'Hold'), ('release', 'Release')], db_index=True, default='credit', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payouts.payout'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['merchant', 'entry_type', 'created_at'], name='idx_ledg_merch_type_cr'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'credit'), ('payout__isnull', True)), models.Q(('entry_type__in', ['hold', 'release']), ('payout__isnull', False)), _connector='OR'), name='ck_ledger_payout_fk_consistency'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('entry_type__in', ['credit', 'release'])), models.Q(('amount__lt', 0), ('entry_type', 'hold')), _connector='OR'), name='ck_ledger_amount_sign_by_type'),
        ),
    ]
