# Generated by Django 5.2.13 on 2026-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgerentry_entry_type_ledgerentry_payout_and_more'),
        ('merchants', '0002_merchantbankaccount_account_name_and_more'),
        ('payouts', '0002_idempotencykey_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ck_ledger_payout_fk_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ck_ledger_amount_sign_by_type',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('hold', 'Hold')], db_index=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'credit'), ('payout__isnull', True)), models.Q(('entry_type', 'hold'), ('payout__isnull', False)), _connector='OR'), name='ck_ledger_payout_fk_consistency'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('entry_type', 'credit')), models.Q(('amount__lt', 0), ('entry_type', 'hold')), _connector='OR'), name='ck_ledger_amount_sign_by_type'),
        ),
    ]
